name: thingsvision
channels:
 - defaults
 - conda-forge
 - pytorch
dependencies:
 - python=3.9
 - numpy=1.22.*
 - ftfy=5.8
 - pandas=1.4.*
 - scikit-image=0.19.*
 - scikit-learn=1.1.*
 - pytorch=1.12.*
 - torchvision=0.13.*
 - tqdm=4.64.0
 - numba=0.56.*
 - matplotlib=3.5.2
 - regex
 - scipy
 - h5py
 - pip
 - pip:
   - open_clip_torch==2.0.* 
   - tensorflow==2.9.*
   - timm==0.6.*
   - codecov
   - pyflakes
   - black 
   - pep8
