title: "THINGSVision"
# Build settings
remote_theme: just-the-docs/just-the-docs

search_enabled: true
search.heading_level: 2
search.previews: 3
search.preview_words_before: 5
search.preview_words_after: 10

heading_anchors: true

aux_links:
  "thingsvision on GitHub":
    - "//github.com/ViCCo-Group/thingsvision"
    -
nav_external_links:
  - title: thingsvision on GitHub
    url: https://github.com/ViCCo-Group/thingsvision

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
